name: Get Github Access Token
description : Get Github Access Token
inputs:
  gh_app_id:
    description: the id of the app to use to get the access token
    required: yes

  gh_install_id: 
    description: the install id of the app to get the access token
    required: yes

  gh_pem_64:
    description: the base64 encoded version of the private pem file (this is a password, keep it secret)
    required: yes
outputs:
  TOKEN:
    description: the temp gh auth token to use
runs:
  using: node16
  main: main.js